version: "3.8"
services:
  coal-monitor:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: coal-monitor:1.0
    ports:
      - "8000:8000"
    networks:
      - coal-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - coal-net
    depends_on:
      - coal-monitor

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - coal-net
    depends_on:
      - prometheus

networks:
  coal-net:
    driver: bridge