apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: coal-devops
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'coal-monitor'
        static_configs:
          - targets: ['host.minikube.internal:8000']