apiVersion: v1
kind: Service
metadata:
  name: coal-monitor
  namespace: coal-devops
  labels:
    app: coal-monitor
spec:
  selector:
    app: coal-monitor

  ports:
    - name: http
      port: 8000
      targetPort: 8000

  type: ClusterIP
