{
 "title": "Coal Monitor Dashboard",
 "tags": [ "coal-monitor" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Coal Monitor Pods Status",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "up{job=\"coal-monitor\"}"
    }
   ]
  },
  {
   "title": "Coal Monitor CPU Usage (cores)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"coal-monitor\"}[1m])"
    }
   ]
  },
  {
   "title": "Coal Monitor Memory Usage (MB)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"coal-monitor\"} / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Coal Monitor Virtual Memory (MB)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 4, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"coal-monitor\"} / 1024 / 1024"
    }
   ]
  }
 ]
}